import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { images } from "@/lib/data";
import { pageMetadata } from "@/lib/site-metadata";

export const metadata: Metadata = pageMetadata({ title: "About Axiom", description: "Application-led industrial systems engineering, manufacturing, and lifecycle support for demanding operating environments.", path: "/about", image: "/images/about-fabrication-detail.webp" });

const capabilities = ["Process equipment fabrication", "Flow and thermal testing", "Controls integration", "Field commissioning"];
const leaders = [
  { name: "Eleanor Hayes", role: "Chief Executive Officer", focus: "Industrial strategy and global operations" },
  { name: "Marcus Chen", role: "Chief Engineering Officer", focus: "Systems engineering and product development" },
  { name: "Amara Okafor", role: "VP, Manufacturing & Quality", focus: "Manufacturing systems and quality assurance" },
];

export default function AboutPage() {
  return <>
    <section className="page-hero"><div className="container"><div className="eyebrow">About Axiom Forge Systems</div><h1 className="display about-hero-title">Industrial systems engineered around operating reality.</h1><p>Axiom brings application-led engineering, disciplined production, and field support together for the environments where reliability matters most.</p></div></section>
    <section className="section section-light"><div className="container about-grid"><div><div className="eyebrow">Company story</div><h2 className="display">Built around the work that matters.</h2><p>From process equipment and flow control to material handling and thermal systems, Axiom starts with the people who operate, maintain, and depend on the equipment. That perspective keeps designs clear to service, resilient in the field, and accountable to measurable outcomes.</p><p>Application teams, manufacturing specialists, and field engineers stay close to the duty cycle, access constraints, materials, utilities, and maintenance plan before a system is released.</p><Link className="button button-dark" href="/request-quote" style={{ marginTop: 24 }}>Work with Axiom</Link></div><div className="media-frame about-image"><Image src="/images/about-fabrication-detail.webp" alt="Precision assembly of a metallic pump component at a workbench" fill sizes="(max-width: 680px) 660px, (max-width: 980px) 100vw, 825px" /></div></div></section>
    <section id="quality" className="section"><div className="container about-grid"><div className="media-frame about-image"><Image src={images.engineer} alt="Engineer working with manufacturing equipment" fill sizes="(max-width: 680px) 660px, (max-width: 980px) 100vw, 825px" /></div><div><div className="eyebrow">Manufacturing & quality assurance</div><h2 className="display">Built to hold a standard.</h2><p>Design reviews, controlled fabrication, documented inspection, and performance testing connect the engineering brief to repeatable field results. Applicable standards and final compliance requirements are confirmed for each real project.</p><div className="capability-list">{capabilities.map((capability, index) => <div key={capability}><span>{String(index + 1).padStart(2, "0")}</span><strong>{capability}</strong></div>)}</div></div></div></section>
    <section className="section section-surface section-border"><div className="container about-grid"><div><div className="eyebrow">Global presence</div><h2 className="display">Engineered in Houston. Supported around the world.</h2></div><div><p>Project teams, manufacturing partners, and field specialists coordinate across regions so commissioning and lifecycle service stay close to the operating site.</p><div className="about-metrics"><div><strong>32</strong><span>Illustrative markets</span></div><div><strong>2,400+</strong><span>Illustrative systems</span></div></div></div></div></section>
    <section className="section section-light"><div className="container"><div className="section-heading"><div><div className="eyebrow">Leadership</div><h2 className="display">Accountability starts at the top.</h2></div><p className="light-copy">A cross-functional leadership team keeps engineering, manufacturing, and field support aligned.</p></div><div className="leadership-grid">{leaders.map((leader) => <article className="leader" key={leader.name}><h3>{leader.name}</h3><strong>{leader.role}</strong><p>{leader.focus}</p></article>)}</div></div></section>
    <div className="cert-strip"><div className="container certs" aria-label="Quality and compliance framework"><div className="cert"><span>QUALITY</span><small>DOCUMENTED GATES</small></div><div className="cert"><span>TRACEABILITY</span><small>INSPECTION RECORDS</small></div><div className="cert"><span>CONFORMITY</span><small>PROJECT REVIEW</small></div><div className="cert"><span>FIELD READY</span><small>SERVICE ACCESS</small></div><div className="cert"><span>RISK AWARE</span><small>HAZARD REVIEW</small></div></div></div>
    <section className="section-tight section-surface"><div className="container"><p className="concept-note" role="note"><strong>Portfolio disclosure.</strong> Axiom Forge Systems is a fictional brand concept created to demonstrate industrial product storytelling and interface design. Company details, people, project outcomes, and quality references are illustrative.</p></div></section>
  </>;
}
