import Image from "next/image";
import Link from "next/link";
import { images, products, industries, projects } from "@/lib/data";
import { ProductCard } from "@/components/product-card";
import { SectionHeading } from "@/components/section-heading";

const stats = [["08", "Product systems"], ["07", "Industries"], ["06", "Illustrative projects"], ["13", "Technical PDFs"]];
const process = ["Application Analysis", "System Engineering", "Manufacturing", "Testing", "Installation", "Lifecycle Support"];
const featuredProducts = [products[0], products[2], products[4], products[6]];

export default function Home() {
  return <>
    <section className="hero"><div className="hero-media"><Image src={images.hero} alt="Industrial manufacturing facility" fill priority sizes="100vw" /></div><div className="hero-content"><div className="eyebrow">Axiom Forge Systems · Industrial engineering</div><h1 className="display">ENGINEERED FOR<br />RELENTLESS INDUSTRY.</h1><p className="hero-intro">High-performance industrial systems engineered for demanding environments, critical infrastructure, and continuous operation.</p><div className="hero-buttons"><Link className="button button-primary" href="/products">Explore Systems <span aria-hidden="true">→</span></Link><Link className="button button-outline" href="/request-quote">Prepare a Brief</Link></div><div className="hero-rule">Industrial equipment · engineered to clarify the next decision</div></div><div className="hero-index">AXIOM / 001</div></section>
    <section className="stats-strip"><div className="container stats-grid">{stats.map(([number, label]) => <div className="stat-item" key={label}><span className="stat-number">{number}</span><span className="stat-label">{label}</span></div>)}</div></section>
    <section className="section section-light"><div className="container intro-grid"><div className="intro-copy"><div className="eyebrow">About Axiom</div><h2 className="display">Built around the environments where failure isn&apos;t an option.</h2><p>Axiom Forge Systems combines application-specific engineering, disciplined manufacturing, and field support for the hard-working middle of critical operations. The work starts with the process, the people, and the conditions the system has to survive.</p><div className="intro-meta"><div><strong>08</strong><span>Product systems</span></div><div><strong>13</strong><span>Technical references</span></div></div><Link className="text-link" href="/about" style={{ marginTop: 32 }}>Our story <span aria-hidden="true">→</span></Link></div><div className="media-frame intro-media"><Image src={images.factory} alt="Industrial factory floor" fill sizes="(max-width: 980px) 100vw, 50vw" /><div className="media-caption">Houston manufacturing floor / operating context</div></div></div></section>
    <section className="section section-surface"><div className="container"><SectionHeading eyebrow="Product systems" title="Systems engineered to perform." description="From individual equipment to integrated process lines, every Axiom system starts with the conditions it has to survive." /><div className="product-grid homepage-product-grid">{featuredProducts.map((product, index) => <ProductCard product={product} featured={index === 0 || index === 3} key={product.slug} />)}</div><Link className="text-link" href="/products" style={{ marginTop: 40 }}>View all products <span aria-hidden="true">→</span></Link></div></section>
    <section id="engineering" className="section section-border"><div className="container process-layout"><div className="process-intro"><div className="eyebrow">Engineering delivery</div><h2 className="display">From concept to commissioning.</h2><p>One accountable engineering narrative from the first application question to the first production run — and every service interval after it.</p></div><div className="timeline">{process.map((item, index) => <div className="timeline-step" key={item}><span className="timeline-step-number">0{index + 1}</span><div><h3>{item}</h3><p>{["Define duty, constraints, and the actual operating envelope.", "Model the system around performance, materials, and access.", "Build to controlled processes and documented quality gates.", "Verify performance before equipment reaches the site.", "Support startup with field teams who know the design.", "Keep performance visible through service and upgrades."][index]}</p></div><span className="timeline-arrow" aria-hidden="true">↗</span></div>)}</div></div></section>
    <section className="section section-surface"><div className="container"><SectionHeading eyebrow="Featured project" title="Measured improvement in the field." description="A modernization scenario designed around a facility&apos;s actual operating conditions — not a catalogue average." /><div className="project-feature"><div className="project-feature-media"><Image src={projects[0].image} alt="Illustrative Rotterdam processing facility" fill sizes="(max-width: 980px) 100vw, 55vw" /></div><div className="project-feature-content"><div className="eyebrow">Illustrative case study · Rotterdam</div><h2 className="display">28% lower energy consumption after system modernization.</h2><p>Rotterdam, Netherlands · Chemical Processing · AF-P900 Process Pump System</p><div className="project-facts"><div className="project-fact"><strong>28%</strong><span>Illustrative energy reduction</span></div><div className="project-fact"><strong>41%</strong><span>Illustrative maintenance change</span></div><div className="project-fact"><strong>99.6%</strong><span>Illustrative availability</span></div></div><Link className="text-link" href={`/projects/${projects[0].slug}`}>View case study <span aria-hidden="true">→</span></Link></div></div><p className="concept-note concept-note-inline">Case study figures are illustrative portfolio scenarios, not verified customer or business outcomes.</p></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Industries" title="Built for the work that keeps the world moving." description="Seven sectors. One engineering standard: specify for the reality of the site." /><div className="image-grid">{industries.slice(0, 3).map((industry) => <Link className="image-card" href={`/industries#${industry.slug}`} key={industry.slug}><Image src={industry.image} alt={`${industry.name} industrial environment`} fill sizes="(max-width: 680px) 100vw, 33vw" /><div className="image-card-content"><div className="eyebrow">0{industries.indexOf(industry) + 1}</div><h3>{industry.name}</h3><p>{industry.description}</p></div></Link>)}</div><Link className="text-link" href="/industries" style={{ marginTop: 40 }}>Explore industries <span aria-hidden="true">→</span></Link></div></section>
    <section className="section section-surface section-border"><div className="container"><SectionHeading eyebrow="Why Axiom" title="Engineering without compromise." /><div className="principles">{[["01", "Application-Specific Engineering", "Equipment configured for your process, not a generic duty point."], ["02", "Global Manufacturing Standards", "Documented quality systems at every design and build stage."], ["03", "Lifecycle Support", "Field-ready support that stays engaged long after commissioning."], ["04", "Documented Quality Gates", "A clear concept framework for repeatable, accountable work."]].map(([number, title, description]) => <div className="principle" key={number}><div className="principle-index">{number}</div><h3>{title}</h3><p>{description}</p></div>)}</div></div></section>
    <div className="cert-strip"><div className="container certs" aria-label="Illustrative quality framework"><div className="cert"><span>QUALITY</span><small>DOCUMENTED GATES</small></div><div className="cert"><span>TRACEABILITY</span><small>INSPECTION RECORDS</small></div><div className="cert"><span>CONFORMITY</span><small>PROJECT REVIEW</small></div><div className="cert"><span>FIELD READY</span><small>SERVICE ACCESS</small></div><div className="cert"><span>RISK AWARE</span><small>HAZARD REVIEW</small></div></div></div>
  </>;
}
