// Fictional company, products, performance claims, projects, and certifications for a portfolio concept.
export type Product = { slug:string; name:string; category:string; shortDescription:string; image:string; specLabel:string; specValue:string; industries:string[]; applications:string[]; overview:string; specs:{label:string;value:string}[] };
export type Project = { slug:string; title:string; industry:string; location:string; system:string; result:string; image:string; summary:string };
export const images = {
  hero:"/images/hero.webp", factory:"/images/factory.webp", pump:"/images/pump.webp",
  pipes:"/images/facility.webp", engineer:"/images/engineer.jpg", machine:"/images/conveyor.webp",
  production:"/images/thermal.webp", facility:"/images/facility.webp", offshore:"/images/marine.webp",
  plant:"/images/thermal.webp", marine:"/images/marine.webp", valve:"/images/valve.webp"
};
const specs = (items:[string,string][]) => items.map(([label,value])=>({label,value}));
export const products: Product[] = [
 {slug:"af-p900-process-pump",name:"AF-P900 Process Pump",category:"Industrial Pumps",shortDescription:"High-performance pumping for demanding process infrastructure.",image:images.pump,specLabel:"Flow rate",specValue:"1,250 m³/h",industries:["Chemical Processing","Water Treatment","Energy"],applications:["Chemical Processing","Water","Energy"],overview:"The AF-P900 is a heavy-duty process pump platform engineered for continuous operation, variable duty cycles, and fluid conditions where reliability is non-negotiable.",specs:specs([["Flow Rate","1,250 m³/h"],["Maximum Pressure","40 bar"],["Operating Temperature","-20°C to 180°C"],["Materials","316 Stainless Steel / Duplex Steel"],["Drive","Direct / VFD-ready"]])},
 {slug:"af-x720-high-pressure-pump",name:"AF-X720 High-Pressure Pump",category:"Industrial Pumps",shortDescription:"Compact high-pressure performance for critical utilities.",image:images.pump,specLabel:"Pressure",specValue:"80 bar",industries:["Energy","Manufacturing","Mining"],applications:["Boiler Feed","Desalination","Process Water"],overview:"A compact high-pressure system for utilities and process applications that demand repeatable output in a tight footprint.",specs:specs([["Flow Rate","720 m³/h"],["Maximum Pressure","80 bar"],["Operating Temperature","-10°C to 160°C"],["Materials","316 Stainless Steel"],["Efficiency","Up to 91%"]])},
 {slug:"vx-400-control-valve",name:"VX-400 Control Valve",category:"Flow Control",shortDescription:"Precision control for critical process infrastructure.",image:images.valve,specLabel:"Size range",specValue:"DN25–DN300",industries:["Chemical Processing","Energy","Water Treatment"],applications:["Flow Regulation","Steam","Slurry"],overview:"The VX-400 provides stable, accurate modulation across demanding flow control applications, with trim packages configured to suit the process medium.",specs:specs([["Size Range","DN25–DN300"],["Pressure Class","PN16–PN100"],["Temperature","-40°C to 400°C"],["Actuation","Pneumatic / Electric"],["Leakage Class","VI"]])},
 {slug:"vx-850-severe-service-valve",name:"VX-850 Severe-Service Valve",category:"Flow Control",shortDescription:"Designed for abrasive, high-temperature process lines.",image:images.valve,specLabel:"Pressure class",specValue:"ASME 1500",industries:["Mining","Chemical Processing","Energy"],applications:["Abrasive Slurry","High Temperature","Gas"],overview:"A severe-service valve engineered around erosion resistance, controllability, and maintainability in harsh operating conditions.",specs:specs([["Size Range","DN50–DN500"],["Pressure Class","ASME 150–1500"],["Temperature","-50°C to 550°C"],["Trim","Tungsten Carbide / Ceramic"],["Body","Forged Alloy Steel"]])},
 {slug:"cx-250-modular-conveyor",name:"CX-250 Modular Conveyor",category:"Conveyor Systems",shortDescription:"Configurable material handling for complex plant layouts.",image:images.machine,specLabel:"Throughput",specValue:"1,200 t/h",industries:["Manufacturing","Mining","Food Processing"],applications:["Bulk Material","Packaged Goods","Process Transfer"],overview:"A modular conveyor architecture that lets operations teams scale throughput, change routing, and keep maintenance accessible.",specs:specs([["Throughput","Up to 1,200 t/h"],["Belt Width","400–1,600 mm"],["Length","Up to 250 m per drive"],["Frame","Painted / Galvanized Steel"],["Controls","PLC / VFD-ready"]])},
 {slug:"cx-900-heavy-duty-conveyor",name:"CX-900 Heavy-Duty Conveyor",category:"Conveyor Systems",shortDescription:"Continuous high-throughput handling for demanding sites.",image:images.machine,specLabel:"Throughput",specValue:"3,500 t/h",industries:["Mining","Marine","Manufacturing"],applications:["Ore","Aggregate","Ship Loading"],overview:"High-capacity conveying built around uptime, serviceability, and safe transfer of abrasive bulk materials.",specs:specs([["Throughput","Up to 3,500 t/h"],["Belt Width","1,200–2,400 mm"],["Incline","Up to 18°"],["Frame","Heavy Structural Steel"],["Monitoring","Condition-ready"]])},
 {slug:"thermacore-t600",name:"ThermaCore T600",category:"Thermal Systems",shortDescription:"Efficient thermal processing with repeatable temperature control.",image:images.plant,specLabel:"Temperature",specValue:"600°C",industries:["Food Processing","Manufacturing","Chemical Processing"],applications:["Drying","Curing","Heat Treatment"],overview:"The T600 couples efficient heat transfer with precise control for production lines where consistent thermal profiles protect quality and yield.",specs:specs([["Operating Temperature","Up to 600°C"],["Chamber Volume","2–48 m³"],["Fuel Options","Gas / Electric"],["Controls","PLC + HMI"],["Recovery","Optional heat recovery"]])},
 {slug:"thermacore-t900",name:"ThermaCore T900",category:"Thermal Systems",shortDescription:"Large-scale thermal processing for energy-intensive lines.",image:images.production,specLabel:"Temperature",specValue:"900°C",industries:["Energy","Manufacturing","Chemical Processing"],applications:["Calcination","Annealing","Thermal Oxidation"],overview:"A high-temperature thermal platform for large, continuous production environments with demanding energy and emissions targets.",specs:specs([["Operating Temperature","Up to 900°C"],["Chamber Volume","20–160 m³"],["Fuel Options","Gas / Electric / Hybrid"],["Controls","Redundant PLC"],["Emissions","Configured to site requirements"]])}
];
export const projects: Project[] = [
 {slug:"rotterdam-processing-facility",title:"Rotterdam Processing Facility",industry:"Chemical Processing",location:"Rotterdam, Netherlands",system:"AF-P900 Process Pump System",result:"28% lower energy consumption",image:images.facility,summary:"A custom pumping modernization restored hydraulic balance across a major processing facility while reducing maintenance exposure."},
 {slug:"norwegian-offshore-terminal",title:"Norwegian Offshore Terminal",industry:"Energy",location:"Stavanger, Norway",system:"VX-850 Severe-Service Valve Package",result:"99.8% availability",image:images.offshore,summary:"Severe-service flow control improved platform uptime across corrosive transfer applications in a remote operating environment."},
 {slug:"texas-water-treatment-expansion",title:"Texas Water Treatment Expansion",industry:"Water Treatment",location:"Houston, Texas",system:"AF-X720 Pump Train",result:"42% more capacity",image:images.pipes,summary:"A staged pump train expansion gave a growing municipality more capacity without interrupting the existing treatment process."},
 {slug:"osaka-automotive-plant",title:"Osaka Automotive Plant",industry:"Manufacturing",location:"Osaka, Japan",system:"ThermaCore T600",result:"17% cycle reduction",image:images.production,summary:"Thermal process engineering shortened cure cycles and stabilized temperature uniformity across a high-volume automotive line."},
 {slug:"queensland-mining-facility",title:"Queensland Mining Facility",industry:"Mining",location:"Queensland, Australia",system:"CX-900 Heavy-Duty Conveyor",result:"3,500 t/h throughput",image:images.machine,summary:"A heavy-duty conveying system increased ore handling capacity while putting safer inspection access at the center of the design."},
 {slug:"singapore-marine-terminal",title:"Singapore Marine Terminal",industry:"Marine",location:"Singapore",system:"CX-250 Modular Conveyor",result:"31% faster transfer",image:images.marine,summary:"A modular transfer system helped a marine terminal adapt routing and throughput without a long shutdown window."}
];
export const industries = [{name:"Energy",slug:"energy",description:"Systems that keep generation, transfer, and processing moving under demanding duty cycles.",image:images.offshore},{name:"Manufacturing",slug:"manufacturing",description:"Integrated equipment for plants where consistency, safety, and throughput are measured every hour.",image:images.production},{name:"Mining",slug:"mining",description:"Rugged material handling and flow systems for abrasive conditions and remote sites.",image:images.machine},{name:"Water Treatment",slug:"water-treatment",description:"Reliable pumping and control for water infrastructure that communities depend on.",image:images.pipes},{name:"Chemical Processing",slug:"chemical-processing",description:"Process equipment specified around fluid behavior, materials, and operating reality.",image:images.facility},{name:"Food Processing",slug:"food-processing",description:"Hygienic, repeatable thermal and handling systems designed around product quality.",image:images.factory},{name:"Marine",slug:"marine",description:"Equipment engineered for saltwater exposure, limited access, and continuous operations.",image:images.marine}];
export const resources = [{type:"Datasheet",title:"AF-P900 Process Pump",description:"Performance range, materials, and configuration options for the AF-P900 platform."},{type:"Engineering guide",title:"Selecting a Pump for Continuous Duty",description:"A practical framework for sizing pumps around real operating conditions."},{type:"Technical article",title:"Understanding Cavitation in Process Pumps",description:"How to recognize, prevent, and troubleshoot cavitation in industrial systems."},{type:"Installation manual",title:"VX-400 Control Valve",description:"Installation, commissioning, and service guidance for the VX-400."},{type:"CAD resource",title:"Modular Conveyor Layout Pack",description:"Reference dimensions for early-stage CX-250 planning and layout coordination."},{type:"Technical article",title:"Reducing Energy in Flow Systems",description:"Where system modernization can create measurable, sustained operating savings."}];
export const navItems = [{label:"Products",href:"/products"},{label:"Industries",href:"/industries"},{label:"Engineering",href:"/#engineering"},{label:"Projects",href:"/projects"},{label:"Resources",href:"/resources"},{label:"About",href:"/about"}];
