export type Product = { slug:string; name:string; category:string; shortDescription:string; image:string; cardImage?:string; specLabel:string; specValue:string; industries:string[]; applications:string[]; overview:string; specs:{label:string;value:string}[] };
export type Project = { slug:string; title:string; industry:string; location:string; system:string; result:string; image:string; summary:string; challenge:string; response:string; technicalDetail:string; metrics:{value:string;label:string}[]; relatedProduct:string };
export const images = {
  hero:"/images/hero-precision.webp", factory:"/images/factory.webp", pump:"/images/pump.webp",
  pipes:"/images/facility.webp", engineer:"/images/engineer.jpg", machine:"/images/conveyor.webp",
  production:"/images/thermal.webp", facility:"/images/facility.webp", offshore:"/images/marine.webp",
  plant:"/images/thermal.webp", marine:"/images/marine.webp", valve:"/images/valve.webp"
};
const specs = (items:[string,string][]) => items.map(([label,value])=>({label,value}));
export const products: Product[] = [
 {slug:"af-p900-process-pump",name:"AF-P900 Process Pump",category:"Industrial Pumps",shortDescription:"High-performance pumping for demanding process infrastructure.",image:images.pump,cardImage:"/images/product-card-pump.webp",specLabel:"Flow rate",specValue:"1,250 m³/h",industries:["Chemical Processing","Water Treatment","Energy"],applications:["Chemical Processing","Water","Energy"],overview:"The AF-P900 is a heavy-duty process pump platform engineered for continuous operation, variable duty cycles, and fluid conditions where reliability is non-negotiable.",specs:specs([["Flow Rate","1,250 m³/h"],["Maximum Pressure","40 bar"],["Operating Temperature","-20°C to 180°C"],["Materials","316 Stainless Steel / Duplex Steel"],["Drive","Direct / VFD-ready"]])},
 {slug:"af-x720-high-pressure-pump",name:"AF-X720 High-Pressure Pump",category:"Industrial Pumps",shortDescription:"Compact high-pressure performance for critical utilities.",image:"/images/pump-x720.webp",cardImage:"/images/product-card-pump-x720.webp",specLabel:"Pressure",specValue:"80 bar",industries:["Energy","Manufacturing","Mining"],applications:["Boiler Feed","Desalination","Process Water"],overview:"A compact high-pressure system for utilities and process applications that demand repeatable output in a tight footprint.",specs:specs([["Flow Rate","720 m³/h"],["Maximum Pressure","80 bar"],["Operating Temperature","-10°C to 160°C"],["Materials","316 Stainless Steel"],["Efficiency","Up to 91%"]])},
 {slug:"vx-400-control-valve",name:"VX-400 Control Valve",category:"Flow Control",shortDescription:"Precision control for critical process infrastructure.",image:images.valve,cardImage:"/images/product-card-valve.webp",specLabel:"Size range",specValue:"DN25–DN300",industries:["Chemical Processing","Energy","Water Treatment"],applications:["Flow Regulation","Steam","Slurry"],overview:"The VX-400 provides stable, accurate modulation across demanding flow control applications, with trim packages configured to suit the process medium.",specs:specs([["Size Range","DN25–DN300"],["Pressure Class","PN16–PN100"],["Temperature","-40°C to 400°C"],["Actuation","Pneumatic / Electric"],["Leakage Class","VI"]])},
 {slug:"vx-850-severe-service-valve",name:"VX-850 Severe-Service Valve",category:"Flow Control",shortDescription:"Designed for abrasive, high-temperature process lines.",image:"/images/valve-vx850.webp",cardImage:"/images/product-card-valve-vx850.webp",specLabel:"Pressure class",specValue:"ASME 1500",industries:["Mining","Chemical Processing","Energy"],applications:["Abrasive Slurry","High Temperature","Gas"],overview:"A severe-service valve engineered around erosion resistance, controllability, and maintainability in harsh operating conditions.",specs:specs([["Size Range","DN50–DN500"],["Pressure Class","ASME 150–1500"],["Temperature","-50°C to 550°C"],["Trim","Tungsten Carbide / Ceramic"],["Body","Forged Alloy Steel"]])},
 {slug:"cx-250-modular-conveyor",name:"CX-250 Modular Conveyor",category:"Conveyor Systems",shortDescription:"Configurable material handling for complex plant layouts.",image:images.machine,cardImage:"/images/product-card-conveyor.webp",specLabel:"Throughput",specValue:"1,200 t/h",industries:["Manufacturing","Mining","Food Processing"],applications:["Bulk Material","Packaged Goods","Process Transfer"],overview:"A modular conveyor architecture that lets operations teams scale throughput, change routing, and keep maintenance accessible.",specs:specs([["Throughput","Up to 1,200 t/h"],["Belt Width","400–1,600 mm"],["Length","Up to 250 m per drive"],["Frame","Painted / Galvanized Steel"],["Controls","PLC / VFD-ready"]])},
 {slug:"cx-900-heavy-duty-conveyor",name:"CX-900 Heavy-Duty Conveyor",category:"Conveyor Systems",shortDescription:"Continuous high-throughput handling for demanding sites.",image:"/images/conveyor-cx900.webp",cardImage:"/images/product-card-conveyor-cx900.webp",specLabel:"Throughput",specValue:"3,500 t/h",industries:["Mining","Marine","Manufacturing"],applications:["Ore","Aggregate","Ship Loading"],overview:"High-capacity conveying built around uptime, serviceability, and safe transfer of abrasive bulk materials.",specs:specs([["Throughput","Up to 3,500 t/h"],["Belt Width","1,200–2,400 mm"],["Incline","Up to 18°"],["Frame","Heavy Structural Steel"],["Monitoring","Condition-ready"]])},
 {slug:"thermacore-t600",name:"ThermaCore T600",category:"Thermal Systems",shortDescription:"Efficient thermal processing with repeatable temperature control.",image:images.plant,cardImage:"/images/product-card-thermal.webp",specLabel:"Temperature",specValue:"600°C",industries:["Food Processing","Manufacturing","Chemical Processing"],applications:["Drying","Curing","Heat Treatment"],overview:"The T600 couples efficient heat transfer with precise control for production lines where consistent thermal profiles protect quality and yield.",specs:specs([["Operating Temperature","Up to 600°C"],["Chamber Volume","2–48 m³"],["Fuel Options","Gas / Electric"],["Controls","PLC + HMI"],["Recovery","Optional heat recovery"]])},
 {slug:"thermacore-t900",name:"ThermaCore T900",category:"Thermal Systems",shortDescription:"Large-scale thermal processing for energy-intensive lines.",image:"/images/thermal-t900.webp",cardImage:"/images/product-card-thermal-t900.webp",specLabel:"Temperature",specValue:"900°C",industries:["Energy","Manufacturing","Chemical Processing"],applications:["Calcination","Annealing","Thermal Oxidation"],overview:"A high-temperature thermal platform for large, continuous production environments with demanding energy and emissions targets.",specs:specs([["Operating Temperature","Up to 900°C"],["Chamber Volume","20–160 m³"],["Fuel Options","Gas / Electric / Hybrid"],["Controls","Redundant PLC"],["Emissions","Configured to site requirements"]])}
];
export const projects: Project[] = [
 {slug:"rotterdam-processing-facility",title:"Rotterdam Processing Facility",industry:"Chemical Processing",location:"Rotterdam, Netherlands",system:"AF-P900 Process Pump System",result:"28% lower energy consumption",image:"/images/project-rotterdam-pump-gallery.webp",summary:"A custom pumping modernization restored hydraulic balance across a major processing facility while reducing maintenance exposure.",challenge:"Aging pumps were forcing the facility to run around hydraulic imbalance, increasing energy draw and creating maintenance windows that interrupted production.",response:"Axiom mapped the existing duty cycle, selected an AF-P900 train, optimized the system curve, integrated VFD control, and supported staged commissioning around live production.",technicalDetail:"A tuned system curve, VFD control, and staged commissioning sequence connected pump selection to the live production constraints.",metrics:[{value:"28%",label:"Energy reduction"},{value:"41%",label:"Lower maintenance cost"},{value:"99.6%",label:"System availability"}],relatedProduct:"af-p900-process-pump"},
 {slug:"norwegian-offshore-terminal",title:"Norwegian Offshore Terminal",industry:"Energy",location:"Stavanger, Norway",system:"VX-850 Severe-Service Valve Package",result:"99.8% availability",image:"/images/project-norway.webp",summary:"Severe-service flow control improved platform uptime across corrosive transfer applications in a remote operating environment.",challenge:"Corrosive transfer service and limited access made valve wear a direct threat to terminal availability.",response:"A severe-service trim package and planned inspection points improved controllability without adding unnecessary maintenance complexity.",technicalDetail:"Tungsten-carbide trim, remote inspection points, and a staged isolation plan kept the intervention within the terminal's restricted access windows.",metrics:[{value:"99.8%",label:"Availability"},{value:"18%",label:"Fewer interventions"},{value:"4.2 yr",label:"Inspection interval"}],relatedProduct:"vx-850-severe-service-valve"},
 {slug:"texas-water-treatment-expansion",title:"Texas Water Treatment Expansion",industry:"Water Treatment",location:"Houston, Texas",system:"AF-X720 Pump Train",result:"42% more capacity",image:"/images/project-texas-water.webp",summary:"A staged pump train expansion gave a growing municipality more capacity without interrupting the existing treatment process.",challenge:"The plant needed more capacity without taking the existing treatment train offline.",response:"A phased pump train and tie-in plan added duty capacity while keeping commissioning windows short and controlled.",technicalDetail:"A parallel pump train, VFD-ready drives, and short tie-in windows allowed the plant to add capacity without taking the original treatment path offline.",metrics:[{value:"42%",label:"More capacity"},{value:"0",label:"Unplanned outages"},{value:"6 mo",label:"Delivery window"}],relatedProduct:"af-x720-high-pressure-pump"},
 {slug:"osaka-automotive-plant",title:"Osaka Automotive Plant",industry:"Manufacturing",location:"Osaka, Japan",system:"ThermaCore T600",result:"17% cycle reduction",image:"/images/project-osaka.webp",summary:"Thermal process engineering shortened cure cycles and stabilized temperature uniformity across a high-volume automotive line.",challenge:"Variable cure profiles were slowing throughput and increasing rework at a high-volume automotive line.",response:"Thermal modeling and revised air distribution stabilized the process profile and gave operators clearer control points.",technicalDetail:"Rebalanced air distribution, revised burner zoning, and tighter sensor placement reduced the temperature spread without changing the line footprint.",metrics:[{value:"17%",label:"Cycle reduction"},{value:"±3°C",label:"Profile variance"},{value:"12%",label:"Less rework"}],relatedProduct:"thermacore-t600"},
 {slug:"queensland-mining-facility",title:"Queensland Mining Facility",industry:"Mining",location:"Queensland, Australia",system:"CX-900 Heavy-Duty Conveyor",result:"3,500 t/h throughput",image:"/images/project-queensland-conveyor.webp",summary:"A heavy-duty conveying system increased ore handling capacity while putting safer inspection access at the center of the design.",challenge:"An aging transfer route constrained throughput and made inspection access unnecessarily hazardous.",response:"The CX-900 layout increased capacity while separating service access from the material path and aligning transfer points.",technicalDetail:"A separated service walkway, tuned transfer chutes, and condition-ready monitoring kept the higher-capacity route accessible for inspection.",metrics:[{value:"3,500",label:"t/h throughput"},{value:"22%",label:"Less spillage"},{value:"31%",label:"Faster inspection"}],relatedProduct:"cx-900-heavy-duty-conveyor"},
 {slug:"singapore-marine-terminal",title:"Singapore Marine Terminal",industry:"Marine",location:"Singapore",system:"CX-250 Modular Conveyor",result:"31% faster transfer",image:"/images/project-singapore-conveyor.webp",summary:"A modular transfer system helped a marine terminal adapt routing and throughput without a long shutdown window.",challenge:"Changing berth schedules demanded a transfer system that could be reconfigured between operating windows.",response:"A modular conveyor layout gave the terminal a repeatable transfer path and service access without a long shutdown.",technicalDetail:"Pinned modular sections, four repeatable routing modes, and a two-week installation sequence reduced the shutdown footprint at the berth.",metrics:[{value:"31%",label:"Faster transfer"},{value:"2 wk",label:"Installation window"},{value:"4",label:"Routing modes"}],relatedProduct:"cx-250-modular-conveyor"}
];
export const industries = [
 {name:"Energy",slug:"energy",description:"Systems that keep generation, transfer, and processing moving under demanding duty cycles.",image:"/images/industry-energy.webp",applications:["Pump systems","Severe-service valves","Thermal equipment","Transfer systems"]},
 {name:"Manufacturing",slug:"manufacturing",description:"Integrated equipment for plants where consistency, safety, and throughput are measured every hour.",image:"/images/industry-manufacturing-precision.webp",applications:["Process utilities","Material handling","Thermal processing","Plant upgrades"]},
 {name:"Mining",slug:"mining",description:"Rugged material handling and flow systems for abrasive conditions and remote sites.",image:"/images/industry-mining-plant.webp",applications:["Ore transfer","Slurry handling","Conveying","Dust control"]},
 {name:"Water Treatment",slug:"water-treatment",description:"Reliable pumping and control for water infrastructure that communities depend on.",image:"/images/industry-water.webp",applications:["Raw water intake","High-lift pumping","Filtration systems","Process control"]},
 {name:"Chemical Processing",slug:"chemical-processing",description:"Process equipment specified around fluid behavior, materials, and operating reality.",image:"/images/industry-chemical-plant.webp",applications:["Process pumping","Corrosive service","Flow control","Thermal systems"]},
 {name:"Food Processing",slug:"food-processing",description:"Hygienic, repeatable thermal and handling systems designed around product quality.",image:"/images/industry-food.webp",applications:["Hygienic transfer","Drying and curing","Packaging lines","Clean utilities"]},
 {name:"Marine",slug:"marine",description:"Equipment engineered for saltwater exposure, limited access, and continuous operations.",image:images.marine,applications:["Ship loading","Ballast systems","Bulk transfer","Terminal upgrades"]}
];
export type Resource = {slug:string;category:string;type:string;title:string;description:string;purpose:string;meta:string;href:string;action:string;download?:boolean};
export const resources: Resource[] = [
 {slug:"af-p900-process-pump",category:"Product datasheets",type:"Product datasheet",title:"AF-P900 Process Pump",description:"Performance range, materials, and configuration options for the AF-P900 platform.",purpose:"Compare the process-pump envelope before an application review.",meta:"PDF · 2 pages · Product datasheet",href:"/af-p900-process-pump.pdf",action:"Download PDF",download:true},
 {slug:"af-x720-high-pressure-pump",category:"Product datasheets",type:"Product datasheet",title:"AF-X720 High-Pressure Pump",description:"Flow, pressure, materials, and efficiency details for the AF-X720 platform.",purpose:"Check high-pressure utility and process-water fit.",meta:"PDF · 2 pages · Product datasheet",href:"/af-x720-high-pressure-pump.pdf",action:"Download PDF",download:true},
 {slug:"vx-400-control-valve",category:"Product datasheets",type:"Product datasheet",title:"VX-400 Control Valve",description:"Size range, pressure class, actuation, and trim options for the VX-400.",purpose:"Review control-valve configuration options with a process team.",meta:"PDF · 2 pages · Product datasheet",href:"/vx-400-control-valve.pdf",action:"Download PDF",download:true},
 {slug:"vx-850-severe-service-valve",category:"Product datasheets",type:"Product datasheet",title:"VX-850 Severe-Service Valve",description:"Severe-service materials, pressure classes, and temperature limits for abrasive lines.",purpose:"Screen severe-service valve requirements before detailed selection.",meta:"PDF · 2 pages · Product datasheet",href:"/vx-850-severe-service-valve.pdf",action:"Download PDF",download:true},
 {slug:"cx-250-modular-conveyor",category:"Product datasheets",type:"Product datasheet",title:"CX-250 Modular Conveyor",description:"Throughput, belt-width, drive-length, and controls information for modular layouts.",purpose:"Coordinate an early material-handling layout.",meta:"PDF · 2 pages · Product datasheet",href:"/cx-250-modular-conveyor.pdf",action:"Download PDF",download:true},
 {slug:"cx-900-heavy-duty-conveyor",category:"Product datasheets",type:"Product datasheet",title:"CX-900 Heavy-Duty Conveyor",description:"Capacity, incline, frame, and condition-monitoring details for high-throughput transfer.",purpose:"Check heavy-duty conveying requirements and service access.",meta:"PDF · 2 pages · Product datasheet",href:"/cx-900-heavy-duty-conveyor.pdf",action:"Download PDF",download:true},
 {slug:"thermacore-t600",category:"Product datasheets",type:"Product datasheet",title:"ThermaCore T600",description:"Operating temperature, chamber volume, fuel, controls, and heat-recovery options.",purpose:"Frame a thermal-process conversation around temperature and volume.",meta:"PDF · 2 pages · Product datasheet",href:"/thermacore-t600.pdf",action:"Download PDF",download:true},
 {slug:"thermacore-t900",category:"Product datasheets",type:"Product datasheet",title:"ThermaCore T900",description:"High-temperature chamber, fuel, controls, and emissions-configuration details.",purpose:"Evaluate a larger thermal platform for continuous production.",meta:"PDF · 2 pages · Product datasheet",href:"/thermacore-t900.pdf",action:"Download PDF",download:true},
 {slug:"selecting-a-pump-for-continuous-duty",category:"Engineering guides",type:"Engineering guide",title:"Selecting a Pump for Continuous Duty",description:"A practical framework for sizing pumps around real operating conditions.",purpose:"Prepare the questions that make pump sizing useful.",meta:"PDF · 2 pages · Engineering guide",href:"/pump-selection-guide.pdf",action:"Download PDF",download:true},
 {slug:"understanding-cavitation",category:"Engineering guides",type:"Technical article",title:"Understanding Cavitation in Process Pumps",description:"How to recognize, prevent, and troubleshoot cavitation in industrial systems.",purpose:"Use as a troubleshooting primer for unstable pump operation.",meta:"PDF · 2 pages · Technical article",href:"/cavitation-guide.pdf",action:"Download PDF",download:true},
 {slug:"reducing-energy-in-flow-systems",category:"Engineering guides",type:"Technical article",title:"Reducing Energy in Flow Systems",description:"Where system modernization can create measurable, sustained operating savings.",purpose:"Identify the system-level questions behind efficiency work.",meta:"PDF · 2 pages · Technical article",href:"/flow-system-efficiency.pdf",action:"Download PDF",download:true},
 {slug:"installation-commissioning-guide",category:"Installation & application references",type:"Installation manual",title:"Installation & Commissioning Guide",description:"A concise sequence for installation planning, commissioning readiness, and handoff.",purpose:"Align site preparation and startup conversations.",meta:"PDF · 2 pages · Installation manual",href:"/installation-commissioning-guide.pdf",action:"Download PDF",download:true},
 {slug:"modular-conveyor-layout-pack",category:"Installation & application references",type:"Concept layout reference",title:"CX-250 Modular Conveyor Layout Pack",description:"Reference dimensions for early-stage CX-250 planning and layout coordination.",purpose:"Check footprint, routing, and service-access assumptions.",meta:"PDF · 2 pages · Concept layout reference",href:"/cx-250-layout-pack.pdf",action:"Download PDF",download:true}
];
export const navItems = [{label:"Products",href:"/products"},{label:"Industries",href:"/industries"},{label:"Engineering",href:"/#engineering"},{label:"Projects",href:"/projects"},{label:"Resources",href:"/resources"},{label:"About",href:"/about"}];
