import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { industries, projects } from "@/lib/data";
import { pageMetadata } from "@/lib/site-metadata";

export const metadata: Metadata = pageMetadata({ title: "Industries", description: "Industrial engineering systems for energy, manufacturing, mining, water, marine, and process industries.", path: "/industries", image: "/images/industry-energy.webp" });

export default function IndustriesPage() {
  return <>
    <section className="page-hero"><div className="container"><div className="eyebrow">Industries</div><h1 className="display">Specified for the world as it is.</h1><p>Every site has a different operating envelope. We bring the process, environment, and people into the engineering brief from day one.</p></div></section>
    <section className="section"><div className="container"><nav className="industry-index" aria-label="Jump to industry"><span className="eyebrow">Jump to sector</span><ol>{industries.map((industry, index) => <li key={industry.slug}><a href={`#${industry.slug}`}><span>{String(index + 1).padStart(2, "0")}</span>{industry.name}</a></li>)}</ol></nav><div className="industry-list">{industries.map((industry, index) => { const relatedProjects = projects.filter((project) => project.industry === industry.name); return <article className="industry-row" id={industry.slug} key={industry.slug}><div className="industry-row-media"><Image src={industry.image} alt={`${industry.name} industrial environment`} fill sizes="(max-width: 680px) 100vw, (max-width: 980px) 45vw, 35vw" /></div><div className="industry-row-content"><div className="eyebrow">{String(index + 1).padStart(2, "0")} · INDUSTRY SYSTEMS</div><h2 className="display">{industry.name}</h2><p>{industry.description}</p><div className="industry-applications">{industry.applications.map((application) => <span key={application}>{application}</span>)}</div><div className="industry-links"><Link className="text-link" href={`/products?industry=${industry.slug}`}>Explore systems <span aria-hidden="true">→</span></Link>{relatedProjects.length > 0 && <div className="industry-project-links"><span>Related project</span>{relatedProjects.map((project) => <Link href={`/projects/${project.slug}`} key={project.slug}>{project.title} <span aria-hidden="true">↗</span></Link>)}</div>}</div></div></article>; })}</div></div></section>
    <section className="section section-light"><div className="container process-layout"><div className="process-intro"><div className="eyebrow">The Axiom approach</div><h2 className="display">Context before catalogue.</h2><p>Our engineers start with the actual duty cycle, access constraints, materials, utilities, and maintenance plan. That is how an equipment choice becomes a system that performs.</p></div><div className="timeline">{["Understand the process", "Model the constraints", "Specify the system", "Support the outcome"].map((label, index) => <div className="timeline-step" key={label}><span className="timeline-step-number">0{index + 1}</span><h3>{label}</h3><span className="timeline-arrow" aria-hidden="true">↗</span></div>)}</div></div></section>
  </>;
}
